[package]
name = "tinymd"
version = "0.1.0"
authors = ["Won Young Chi <wonyoung.chi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
